@startuml ClassDiagramRandom

interface RandomNumberGenerator {
    + name : String
    + generateInt() : int
    + generateDouble() : double
    + getName() : String
}

class LinearCongruentialGenerator {
    
}

class MiddleSquareMethode {

}

class XORShiftGenerator {

}

LinearCongruentialGenerator ..|> RandomNumberGenerator
MiddleSquareMethode ..|> RandomNumberGenerator
XORShiftGenerator ..|> RandomNumberGenerator

@enduml